apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opensearch-dashboards
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qensus-labs-testdrive-dashboards
            port:
              number: 5601
